# Base configs
baseurl: "https://hervster.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Pictures by Herve Nyemeck"
subtitle: "See the world through my eyes!"
author: "Herve Nyemeck"
header:
 title: "Photography"
 subtitle: "by Herve Nyemeck"
footer:
 name: "Hey, I'm Herve."
 bio: "I like shooting things. With my camera. Also code in my freetime (on occasion). Thought this would be a better space for my pictures."
 github: My "<a href=\"https://github.com/ramswaroop/photography\">github</a>"
web_design: "AJ"
social_urls:
  twitter: "https://twitter.com/hervster1"
  instagram: "https://www.instagram.com/hervsterino"
  linkedin: "https://in.linkedin.com/in/hnyemeck"
  github: "https://www.github.com/hervster"
